In [ ]:
# Objective 1: Print "Hello World" in CoLab
print("Hello World!")

Hello World!


In [ ]:
# Objective 2: Perform matrix multiplication in PyTorch
import torch

# it is always a good idea to start with a random seed
torch.manual_seed(605)

a = torch.randn(2, 3)
b = torch.randn(3, 5)
print(a)
print(b)

tensor([[ 1.1412, -1.1903, -0.2589],
        [ 0.0178,  0.4158,  0.0207]])
tensor([[-0.9021,  0.3112,  0.1275, -0.3989, -1.2741],
        [ 1.2167, -2.5898,  1.5967, -1.8627,  1.0125],
        [-1.5573, -0.0671,  0.4498, -0.5815, -0.5709]])


In [ ]:
c = a @ b # c = a.matmul(b) also torch.matmul(a, b)
print(c.size())
print(c)

torch.Size([2, 5])
tensor([[-2.0745,  3.4550, -1.8714,  1.9125, -2.5113],
        [ 0.4577, -1.0728,  0.6755, -0.7937,  0.3865]])


In [ ]:
c2 = b.t() @ a.t()
print(c2.t().size())
print(c2.t())

torch.Size([2, 5])
tensor([[-2.0745,  3.4550, -1.8714,  1.9125, -2.5113],
        [ 0.4577, -1.0728,  0.6755, -0.7937,  0.3865]])


In [ ]:
# Often times, we want to paramterize b, which means we want to treat it as a variable than an input.
from torch import nn
# if bias=True (default), a bias vector is added
b_layer = nn.Linear(3, 5, bias=False)
# Note that linear weight is trasponsed because it is applied at the front instead of at the back.
print(b_layer.weight.size())
print(b_layer.weight)

torch.Size([5, 3])
Parameter containing:
tensor([[-0.0950,  0.2956,  0.3553],
        [ 0.2678, -0.0171, -0.4928],
        [-0.1845, -0.2508,  0.2816],
        [ 0.3971, -0.2691, -0.0812],
        [ 0.2856, -0.1239,  0.1443]], requires_grad=True)


In [ ]:
c_1 = b_layer(a)
# use .t() for transposing the matrix
c_2 = a.matmul(b_layer.weight.t())
print(c_1)
print(c_2)

tensor([[-0.5523,  0.4535,  0.0151,  0.7945,  0.4361],
        [ 0.1286, -0.0126, -0.1018, -0.1065, -0.0435]], grad_fn=<MmBackward0>)
tensor([[-0.5523,  0.4535,  0.0151,  0.7945,  0.4361],
        [ 0.1286, -0.0126, -0.1018, -0.1065, -0.0435]], grad_fn=<MmBackward0>)


In [ ]:
# Objective 3: Perform differentiation in PyTorch
y = c_1.sum()
y.backward()
print(b_layer.weight.grad.size())
print(b_layer.weight.grad)

torch.Size([5, 3])
tensor([[ 1.1589, -0.7744, -0.2382],
        [ 1.1589, -0.7744, -0.2382],
        [ 1.1589, -0.7744, -0.2382],
        [ 1.1589, -0.7744, -0.2382],
        [ 1.1589, -0.7744, -0.2382]])


In [ ]:
# Objective 4: Create a simple weight-to-height dataset
# assume h = 0.01 * weight + 1.1
# inductive bias: h = a * w + b
# N is the size of the dataset
N = 5
# First, create uniform inputs between 40 and 100
x = torch.rand(N, 1) * 60 + 40
print(x)

tensor([[86.7988],
        [44.6476],
        [69.7319],
        [61.6121],
        [64.0459]])


In [ ]:
# Now, given the inputs, create labels with standard deviation of 0.05m (5cm)
y = 0.01 * x + 1.1 + torch.randn(N, 1) * 0.05
print(y)

tensor([[1.6587],
        [1.5462],
        [1.8695],
        [1.7665],
        [1.7282]])


In [ ]:
# Objective 5: Create a single-layer model
# Note that we have two parameters: weight and bias
layer = nn.Linear(1, 1)
print(layer.weight)
print(layer.bias)
# .parameters() is a generator, so you need to list it.
print(list(layer.parameters()))

Parameter containing:
tensor([[0.0163]], requires_grad=True)
Parameter containing:
tensor([0.1583], requires_grad=True)
[Parameter containing:
tensor([[0.0163]], requires_grad=True), Parameter containing:
tensor([0.1583], requires_grad=True)]


In [ ]:
pred = layer(x)
print(pred)

tensor([[1.5713],
        [0.8851],
        [1.2935],
        [1.1613],
        [1.2009]], grad_fn=<AddmmBackward0>)
